CC		 = o64-gcc
CFLAGS  ?= -Wall -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES) -arch x86_64
LDFLAGS ?= -lpthread -lssl -lcrypto -ldl -lm -lstdc++ -L. -arch x86_64 -mmacosx-version-min=10.5
OS		 = Darwin

OBJ			= bin/osx
EXECUTABLE =  bin/raop_play-osx

include Makefile

